In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
print("Imported Libraries Successfully")

Imported Libraries Successfully

In [21]:
df = pd.read_csv("new_movies.csv", low_memory= False, index_col= 0)
# df.head()

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, tt4710316 to tt0620913
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            100000 non-null  object
 1   year            100000 non-null  object
 2   rating          100000 non-null  float64
 3   certificate     100000 non-null  object
 4   duration        100000 non-null  object
 5   genre           100000 non-null  object
 6   votes           100000 non-null  object
 7   gross_income    100000 non-null  object
 8   directors_id    100000 non-null  object
 9   directors_name  100000 non-null  object
 10  stars_id        100000 non-null  object
 11  stars_name      100000 non-null  object
 12  description     100000 non-null  object
dtypes: float64(1), object(12)
memory usage: 10.7+ MB

In [23]:
df.isna().sum()

name              0
year              0
rating            0
certificate       0
duration          0
genre             0
votes             0
gross_income      0
directors_id      0
directors_name    0
stars_id          0
stars_name        0
description       0
dtype: int64

In [24]:
df.dropna(inplace=True)

In [25]:
df['year'] = df['year'].str.strip('()')

In [26]:
df.head(10)

,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
id,,,,,,,,,,,,,
tt4710316,Best in Sex: 2015 AVN Awards,2015 TV Special,4.0,TV-MA,94 min,"Adult, News",124.0,0,nm1624094,Gary Miller,"nm4766272,nm2670531,nm4920605,nm6284246","Farrah Laurel Abraham,Asa Akira,Anikka Albrite...",The hottest adult stars and top adult movies a...
tt1281857,Naughty Novelist,2008 Video,3.8,Not Certified,88 min,Adult,174.0,0,nm0045256,John Bacchus,"nm0128986,nm1969196,nm0451160,nm6130462","Darian Caine,Jackie Stevens,A.J. Khan,Arrora",Darian is a successful journalist but when she...
tt2294954,2011 AVN Awards Show,2011 TV Special,5.7,Not Certified,83 min,"Adult, News",39.0,0,"nm1624094,nm0754845","Gary Miller,Timothy E. Sabo","nm2200343,nm2670531,nm1267549,nm3585599","Aubrey Addams,Asa Akira,Monique Alexander,Rave...",Add a Plot
tt6843596,Best in Sex: 2017 AVN Awards,2017 TV Special,4.9,TV-MA,87 min,"Adult, News",225.0,0,nm1624094,Gary Miller,"nm5221471,nm2670531,nm4920605,nm3038816","Amirah Adara,Asa Akira,Anikka Albrite,Britney ...","Considered the industry's highest honor, the A..."
tt3705604,AVN Awards 2014,2014 TV Special,6.7,R,82 min,"Adult, News",101.0,0,nm1624094,Gary Miller,"nm2670531,nm4920605,nm6284246,nm3992720","Asa Akira,Anikka Albrite,August Ames,Jessie An...",Erotic filmmaking superstars Chanel Preston an...
tt12741008,Couples Guest House,2020â€“,6.0,Not Certified,0 min,"Adult, Romance",54.0,0,Anonymous,nm0000000,"nm11750590,nm11750463,nm11750588,nm11750589","Jayesh Arora,Rakhi Sharma,Ekta Killar,Vinod Go...",2 romantic couples moves out for a trip and st...
tt0207195,Wadd: The Life & Times of John C. Holmes,1999,6.8,NC-17,105 min,"Documentary, Adult, Biography",907.0,0,nm0256178,Wesley Emerson,"nm0001360,nm1720643,nm0024662,nm1632456","John Holmes,Linda Adrain,Bill Amerson,Denise A...","Friends, enemies, acquaintances, and family of..."
tt3450356,The Sex Awards,2014 TV Special,7.1,TV-MA,72 min,"Adult, News",74.0,0,nm6563445,Doug Fresh,"nm0236928,nm5190883,nm5047567,nm2670531","Jessica Drake,Veruca James,Penny Pax,Asa Akira",Who will be crowned the first Porn Star of the...
tt7630866,Modern Romance,2017 Video,7.3,Not Certified,103 min,"Adult, Romance",28.0,0,nm1754477,Holly Randall,"nm8760098,nm6284246,nm3631553,nm3742007","Nancy Ace,August Ames,Bill Bailey,Vicki Chase",Add a Plot
tt0329254,The Kama Sutra of Vatsyayana,1993 Video,2.9,Unrated,60 min,"Documentary, Adult",25.0,0,nm1227435,Horace Edgar,"nm1228328,nm0598940,nm1226431,nm0909145","Mohinderjeet,Tony Montana,Cheyenne,Marc Wallice",Add a Plot

In [27]:
df[['year', 'type']] = df['year'].str.split(' ', n = 1, expand=True)

In [28]:
df.tail()

,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description,type
id,,,,,,,,,,,,,,
tt0620885,Knight Rider,1982â€“1986,7.1,TV-PG,49 min,"Action, Crime, Drama",221,0,nm0104096,Bob Bralver,"nm0001327,nm0611811,nm0390258,nm0263040","David Hasselhoff,Edward Mulhare,Rebecca Holden...",Michael investigates a series of robberies in ...,None
tt0620890,Knightwatch,1988â€“1989,11.0,Not Certified,0 min,"Crime, Drama",0,0,nm0838198,Kevin Rodney Sullivan,"nm0000973,nm0505226,nm0291405,nm0891088","Benjamin Bratt,Calvin Levels,Don Franklin,Pari...",Add a Plot,None
tt0620891,Knightwatch,1988â€“1989,11.0,Not Certified,0 min,"Crime, Drama",0,0,nm0897794,Reynaldo Villalobos,"nm0000973,nm0505226,nm0291405,nm0891088","Benjamin Bratt,Calvin Levels,Don Franklin,Pari...",Add a Plot,None
tt0620912,The Knock,1994â€“2000,11.0,Not Certified,0 min,"Crime, Action, Drama",0,0,nm0693726,Gerry Poulson,"nm0832695,nm0498510,nm0869750,nm0089202","Malcolm Storry,Caroline Lee-Johnson,Steve Tous...",Danson buries Noveski's body near the smugglin...,None
tt0620913,The Knock,1994â€“2000,11.0,Not Certified,0 min,"Crime, Action, Drama",0,0,nm0235196,Nigel Douglas,"nm0113338,nm0869750,nm1528465,nm0639774","Daniel Brown,Steve Toussaint,Tim Scott-Walker,...",An illegal arms racket is discovered after a s...,None

In [29]:
df['year'] = df['year'].str.rstrip('â€“')
df['duration'] = df['duration'].str.rstrip(' min')

In [30]:
df.tail(10)

,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description,type
id,,,,,,,,,,,,,,
tt0620880,Knight Rider,1982â€“1986,6.7,TV-PG,49,"Action, Crime, Drama",285,0,nm0002887,Alan Myerson,"nm0001327,nm0611811,nm0574253,nm0244359","David Hasselhoff,Edward Mulhare,Patricia McPhe...",Michael is investigating the death of glamor m...,None
tt0620881,Knight Rider,1982â€“1986,6.8,TV-PG,49,"Action, Crime, Drama",205,0,nm0047094,Charles Bail,"nm0001327,nm0611811,nm0574253,nm0663602","David Hasselhoff,Edward Mulhare,Patricia McPhe...",A gang of bikers with a knack for high-jacking...,None
tt0620882,Knight Rider,1982â€“1986,7.6,TV-PG,48,"Action, Crime, Drama",410,0,nm0822570,Paul Stanley,"nm0001327,nm0611811,nm0574253,nm0761836","David Hasselhoff,Edward Mulhare,Patricia McPhe...",Two small time crooks steal and activate KITT'...,None
tt0620883,Knight Rider,1982â€“1986,6.7,TV-PG,49,"Action, Crime, Drama",220,0,nm0271708,Georg Fenady,"nm0001327,nm0611811,nm0574253,nm0663602","David Hasselhoff,Edward Mulhare,Patricia McPhe...",Michael walks in on a robbery at Towers Gemsto...,None
tt0620884,Knight Rider,1982â€“1986,7.2,TV-PG,49,"Action, Crime, Drama",304,0,nm0463926,Winrich Kolbe,"nm0001327,nm0611811,nm0574253,nm0382692","David Hasselhoff,Edward Mulhare,Patricia McPhe...","When Stephanie Mason, the woman Michael Knight...",None
tt0620885,Knight Rider,1982â€“1986,7.1,TV-PG,49,"Action, Crime, Drama",221,0,nm0104096,Bob Bralver,"nm0001327,nm0611811,nm0390258,nm0263040","David Hasselhoff,Edward Mulhare,Rebecca Holden...",Michael investigates a series of robberies in ...,None
tt0620890,Knightwatch,1988â€“1989,11.0,Not Certified,0,"Crime, Drama",0,0,nm0838198,Kevin Rodney Sullivan,"nm0000973,nm0505226,nm0291405,nm0891088","Benjamin Bratt,Calvin Levels,Don Franklin,Pari...",Add a Plot,None
tt0620891,Knightwatch,1988â€“1989,11.0,Not Certified,0,"Crime, Drama",0,0,nm0897794,Reynaldo Villalobos,"nm0000973,nm0505226,nm0291405,nm0891088","Benjamin Bratt,Calvin Levels,Don Franklin,Pari...",Add a Plot,None
tt0620912,The Knock,1994â€“2000,11.0,Not Certified,0,"Crime, Action, Drama",0,0,nm0693726,Gerry Poulson,"nm0832695,nm0498510,nm0869750,nm0089202","Malcolm Storry,Caroline Lee-Johnson,Steve Tous...",Danson buries Noveski's body near the smugglin...,None
tt0620913,The Knock,1994â€“2000,11.0,Not Certified,0,"Crime, Action, Drama",0,0,nm0235196,Nigel Douglas,"nm0113338,nm0869750,nm1528465,nm0639774","Daniel Brown,Steve Toussaint,Tim Scott-Walker,...",An illegal arms racket is discovered after a s...,None

In [31]:
df['duration'] = df['duration'].str.replace(',', '').astype(float)
df['gross_income'] = df['gross_income'].str.replace(',', '').str.replace('$', '').str.replace('M', '').astype(float)
df['votes'] = df['votes'].str.replace(',', '').astype(float)

In [32]:
df.describe()

              rating       duration         votes  gross_income
count  100000.000000  100000.000000  1.000000e+05  1.000000e+05
mean        8.512057      45.273000  2.348855e+03  1.157382e+06
std         2.379297      49.912399  2.851999e+04  1.038459e+07
min         1.000000       0.000000  0.000000e+00  0.000000e+00
25%         6.600000       0.000000  0.000000e+00  0.000000e+00
50%         8.000000      30.000000  1.100000e+01  0.000000e+00
75%        11.000000      86.000000  8.800000e+01  0.000000e+00
max        11.000000    2150.000000  2.574832e+06  5.348584e+08

In [33]:
df.isna().sum()

name                  0
year                  0
rating                0
certificate           0
duration              0
genre                 0
votes                 0
gross_income          0
directors_id          0
directors_name        0
stars_id              0
stars_name            0
description           0
type              72188
dtype: int64

In [34]:
# df['type'].unique()
df.drop(columns=['type'], axis = 1, inplace=True)

In [35]:
df.isna().sum()

name              0
year              0
rating            0
certificate       0
duration          0
genre             0
votes             0
gross_income      0
directors_id      0
directors_name    0
stars_id          0
stars_name        0
description       0
dtype: int64

In [36]:
df.columns

Index(['name', 'year', 'rating', 'certificate', 'duration', 'genre', 'votes',
       'gross_income', 'directors_id', 'directors_name', 'stars_id',
       'stars_name', 'description'],
      dtype='object')

# Content Based Recommender System

In [37]:
new_df = df.head(10000)

In [39]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

def recommend_videos(search_query):
    new_df_copy = new_df.copy()  # Create a deep copy of the DataFrame
    new_df_copy['content'] = new_df_copy['genre'] + ' ' + new_df_copy['name'] + ' ' + new_df_copy['description'] + ' ' + new_df_copy['year'].astype(str) + ' ' + new_df_copy['rating'].astype(str) + ' ' + new_df_copy['directors_name'] + ' ' + new_df_copy['stars_name'] + new_df_copy['certificate']
    new_df_copy['content'] = new_df_copy['content'].str.lower()

    tfidf_vectorizer = TfidfVectorizer(stop_words='english')
    tfidf_matrix = tfidf_vectorizer.fit_transform(new_df_copy['content'])

    cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

    query_vector = tfidf_vectorizer.transform([search_query])
    cosine_scores = linear_kernel(query_vector, tfidf_matrix)

    video_indices = cosine_scores.argsort()[0][::-1]

    recommended_videos = new_df_copy.iloc[video_indices[:10]][['name']].values.tolist()

    return recommended_videos

# Example usage:
search_query = input("Enter the genre, movie name, description, year, rating, director name, star name, of the movies you are searching for: ")
recommended_videos = recommend_videos(search_query)

if recommended_videos:
    for name in recommended_videos:
        print(f"Title: {name[0]}")
else:
    print("No videos found matching your query. Please try a different search.")

Title: Man on Wire
Title: The Wire
Title: Wire in the Blood
Title: Bite Club
Title: Bad Guy
Title: Strangeways Here We Come
Title: World on a Wire
Title: Shark
Title: Fingers
Title: Pieta